FROM apache/airflow:2.0.1

#RUN pip install docker && \
#    pip install selenium && \
#    pip install bs4 && \
#    pip install pandas && \
#    pip install pymongo && \
#    pip install requests && \
#    pip install swifter && \
#    pip install numpy && \
#    pip install lxml && \
#    pip install flask-bcrypt && \
#    pip install boto3
#



